BM-3 Added Login and Signup functionality and setup database partially
umair-khalid-brainx/social_media_demo pull request #1
Opened 2022-11-25 13:28 UTC by umair-khalid-brainx

2022-11-25 21:16 UTC, usama-javaid-brainx requested changes

2022-11-25 21:16 UTC, usama-javaid-brainx commented on .idea/workspace.xml
> +      <change beforePath="$PROJECT_DIR$/Gemfile" beforeDir="false" afterPath="$PROJECT_DIR$/Gemfile" afterDir="false" />
you need to put all IDE configuration in git ignore do that for all idea files

2022-11-25 21:16 UTC, usama-javaid-brainx commented on app/assets/stylesheets/main.css
> +.error {
class name must be appropriate like error-message if you are displaying error messages

2022-11-25 21:16 UTC, usama-javaid-brainx commented on app/assets/stylesheets/main.css
> +    margin-right: 40% !important;
instead of setting margin why not you use text-center

2022-11-25 21:16 UTC, usama-javaid-brainx commented on app/controllers/posts_controller.rb
> +end
why do we have posts in login sign up PR ?

2022-11-25 21:16 UTC, usama-javaid-brainx commented on app/helpers/posts_helper.rb
> +end
remove all helpers if you are not using them I have told you earlier as well

2022-11-25 21:16 UTC, usama-javaid-brainx commented on app/models/user.rb
> +  validates :phone_number, uniqueness: true
what about email? email should also be unique

2022-11-25 21:16 UTC, usama-javaid-brainx commented on app/models/user.rb
> +  has_many :posts
use dependent destroy here as well

2022-11-25 21:16 UTC, usama-javaid-brainx commented on app/views/devise/confirmations/new.html.erb
> +  <div class="actions">
remove all devise views which we are not using

2022-11-25 21:16 UTC, usama-javaid-brainx commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
why we use stylesheet_link_tag in body?

2022-11-25 21:16 UTC, usama-javaid-brainx commented on db/migrate/20221125101005_create_posts.rb
> +end
why we have empty migration here ?

2022-11-25 21:16 UTC, usama-javaid-brainx commented on test/controllers/posts_controller_test.rb
> +end
remove all the test controllers as you are not using it

2022-11-28 06:02 UTC, umair-khalid-brainx commented on app/assets/stylesheets/main.css
> +    margin-right: 40% !important;
I does not work, the work then takes width of full screen, and on smaller width it stays on left side.

2022-11-28 06:02 UTC, umair-khalid-brainx commented on app/controllers/posts_controller.rb
> +end
Added it for testing purposes of signout button

2022-11-28 06:04 UTC, umair-khalid-brainx commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
it does not import otherwise, only bootstrap works

2022-11-28 06:05 UTC, umair-khalid-brainx commented on db/migrate/20221125101005_create_posts.rb
> +end
testing purposes of sign out button

2022-11-28 06:10 UTC, umair-khalid-brainx commented on app/models/user.rb
> +  validates :phone_number, uniqueness: true
devise handles that that is why i did not put it

2022-11-28 09:20 UTC, merged